//////////////////////////////////////////////////////////////////////////////
// Arma 3 Mission Skeleton by longbow
// version 1.3
// This is an autogenerated file
//////////////////////////////////////////////////////////////////////////////
save = ["SaveMission","Сохранить трофеи","",{[true, 30, grad_trigger] call grad_persistence_fnc_saveMission;},{true},{}] call ace_interact_menu_fnc_createAction; 

while {true} do {
	sleep 1800;
	[false, 30, grad_trigger] call grad_persistence_fnc_saveMission;
};